[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
evm_version = 'cancun'


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
fs_permissions = [{ access = "read", path = "./" }]

[profile.deploy]
optimizer = true
optimizer_runs = 200
evm_version = 'cancun'

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"
holesky = "${RPC_HOLESKY}"
arbitrum = "${RPC_ARBITRUM}"
arbitrum_sepolia = "${RPC_ARBITRUM_SEPOLIA}"
base = "${RPC_BASE}"
base_sepolia = "${RPC_BASE_SEPOLIA}"
scroll = "${RPC_SCROLL}"
scroll_sepolia = "${RPC_SCROLL_SEPOLIA}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY_MAINNET}", url = "${ETHERSCAN_API_URL_MAINNET}" }
sepolia = { key = "${ETHERSCAN_API_KEY_SEPOLIA}", url = "${ETHERSCAN_API_URL_SEPOLIA}" }
holesky = { key = "${ETHERSCAN_API_KEY_HOLESKY}", url = "${ETHERSCAN_API_URL_HOLESKY}" }
arbitrum = { key = "${ETHERSCAN_API_KEY_ARBITRUM}", url = "${ETHERSCAN_API_URL_ARBITRUM}" }
arbitrum_sepolia = { key = "${ETHERSCAN_API_KEY_ARBITRUM_SEPOLIA}", url = "${ETHERSCAN_API_URL_ARBITRUM_SEPOLIA}" }
base = { key = "${ETHERSCAN_API_KEY_BASE}", url = "${ETHERSCAN_API_URL_BASE}" }
base_sepolia = { key = "${ETHERSCAN_API_KEY_BASE_SEPOLIA}", url = "${ETHERSCAN_API_URL_BASE_SEPOLIA}", chain = 84532 }
scroll = { key = "${ETHERSCAN_API_KEY_SCROLL}", url = "${ETHERSCAN_API_URL_SCROLL}" }
scroll_sepolia = { key = "${ETHERSCAN_API_KEY_SCROLL_SEPOLIA}", url = "${ETHERSCAN_API_URL_SCROLL_SEPOLIA}" }
